package com.app.pojo;
// Generated 27 Nov, 2018 4:45:20 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "bdm")
public class Book implements java.io.Serializable {

	private Integer id;
	private Languages languages;
	private Type type;
	private String name;
	private int price;
	private Set<CbDetails> cbDetailses = new HashSet<CbDetails>(0);
	private Set<Inventry> inventries = new HashSet<Inventry>(0);

	public Book() {
	}

	public Book(Languages languages, Type type, String name, int price) {
		this.languages = languages;
		this.type = type;
		this.name = name;
		this.price = price;
	}

	public Book(Languages languages, Type type, String name, int price, Set<CbDetails> cbDetailses,
			Set<Inventry> inventries) {
		this.languages = languages;
		this.type = type;
		this.name = name;
		this.price = price;
		this.cbDetailses = cbDetailses;
		this.inventries = inventries;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lang", nullable = false)
	public Languages getLanguages() {
		return this.languages;
	}

	public void setLanguages(Languages languages) {
		this.languages = languages;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type", nullable = false)
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<CbDetails> getCbDetailses() {
		return this.cbDetailses;
	}

	public void setCbDetailses(Set<CbDetails> cbDetailses) {
		this.cbDetailses = cbDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<Inventry> getInventries() {
		return this.inventries;
	}

	public void setInventries(Set<Inventry> inventries) {
		this.inventries = inventries;
	}

}
