package com.app.Center;
// Generated 27 Nov, 2018 4:45:20 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.app.pojo.User;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Center generated by hbm2java
 */
@Entity
@Table(name = "center", catalog = "bdm")
public class Center implements java.io.Serializable {

	private Integer id;
	private String name;
	private String pm;
	private String location;
	private String pocDetails;
	
	@JsonIgnore
	private transient Set<User> users = new HashSet<User>(0);

	public Center() {
	}

	public Center(String name, String pm, String location, String pocDetails) {
		this.name = name;
		this.pm = pm;
		this.location = location;
		this.pocDetails = pocDetails;
	}

	public Center(String name, String pm, String location, String pocDetails, Set<User> users) {
		this.name = name;
		this.pm = pm;
		this.location = location;
		this.pocDetails = pocDetails;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PM", nullable = false, length = 100)
	public String getPm() {
		return this.pm;
	}

	public void setPm(String pm) {
		this.pm = pm;
	}

	@Column(name = "location", nullable = false, length = 200)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "POC details", nullable = false, length = 300)
	public String getPocDetails() {
		return this.pocDetails;
	}

	public void setPocDetails(String pocDetails) {
		this.pocDetails = pocDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "center")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
