package com.app.Inventry;
// Generated 29 Nov, 2018 1:33:50 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.app.Book.Book;
import com.app.Center.Center;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIdentityReference;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Inventry generated by hbm2java
 */
@Entity
@Table(name = "inventry", catalog = "bdm")
public class Inventry implements java.io.Serializable {

	private Integer id;
	@JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="id",scope = Book.class)
	@JsonIdentityReference(alwaysAsId=true)
	private Book book;
	private int quantity;
	@JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="id",scope = Center.class)
	@JsonIdentityReference(alwaysAsId=true)
	private Set<Center> centers = new HashSet<Center>(0);

	public Inventry() {
	}

	public Inventry(Book book, int quantity) {
		this.book = book;
		this.quantity = quantity;
	}

	public Inventry(Book book, int quantity, Set<Center> centers) {
		this.book = book;
		this.quantity = quantity;
		this.centers = centers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book", nullable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inventry")
	public Set<Center> getCenters() {
		return this.centers;
	}

	public void setCenters(Set<Center> centers) {
		this.centers = centers;
	}

}
